// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export class Config {
    "agents": { [_ in string]?: types$0.AgentConfig | null };
    "providers": { [_ in string]?: types$0.ProviderConfig | null };
    "channels": { [_ in string]?: types$0.ChannelConfig | null };
    "skill": types$0.SkillConfig;
    "browser": types$0.BrowserConfig;
    "live2d": types$0.Live2DConfig;
    "mcp_servers": { [_ in string]?: types$0.McpConfig | null };

    /** Creates a new Config instance. */
    constructor($$source: Partial<Config> = {}) {
        if (!("agents" in $$source)) {
            this["agents"] = {};
        }
        if (!("providers" in $$source)) {
            this["providers"] = {};
        }
        if (!("channels" in $$source)) {
            this["channels"] = {};
        }
        if (!("skill" in $$source)) {
            this["skill"] = (new types$0.SkillConfig());
        }
        if (!("browser" in $$source)) {
            this["browser"] = (new types$0.BrowserConfig());
        }
        if (!("live2d" in $$source)) {
            this["live2d"] = (new types$0.Live2DConfig());
        }
        if (!("mcp_servers" in $$source)) {
            this["mcp_servers"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     */
    static createFrom($$source: any = {}): Config {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType9;
        const $$createField4_0 = $$createType10;
        const $$createField5_0 = $$createType11;
        const $$createField6_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("agents" in $$parsedSource) {
            $$parsedSource["agents"] = $$createField0_0($$parsedSource["agents"]);
        }
        if ("providers" in $$parsedSource) {
            $$parsedSource["providers"] = $$createField1_0($$parsedSource["providers"]);
        }
        if ("channels" in $$parsedSource) {
            $$parsedSource["channels"] = $$createField2_0($$parsedSource["channels"]);
        }
        if ("skill" in $$parsedSource) {
            $$parsedSource["skill"] = $$createField3_0($$parsedSource["skill"]);
        }
        if ("browser" in $$parsedSource) {
            $$parsedSource["browser"] = $$createField4_0($$parsedSource["browser"]);
        }
        if ("live2d" in $$parsedSource) {
            $$parsedSource["live2d"] = $$createField5_0($$parsedSource["live2d"]);
        }
        if ("mcp_servers" in $$parsedSource) {
            $$parsedSource["mcp_servers"] = $$createField6_0($$parsedSource["mcp_servers"]);
        }
        return new Config($$parsedSource as Partial<Config>);
    }
}

// Private type creation functions
const $$createType0 = types$0.AgentConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = types$0.ProviderConfig.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Map($Create.Any, $$createType4);
const $$createType6 = types$0.ChannelConfig.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Map($Create.Any, $$createType7);
const $$createType9 = types$0.SkillConfig.createFrom;
const $$createType10 = types$0.BrowserConfig.createFrom;
const $$createType11 = types$0.Live2DConfig.createFrom;
const $$createType12 = types$0.McpConfig.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Map($Create.Any, $$createType13);
