// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class AgentConfig {
    "id": string;
    "agent_name": string;
    "workspace": string;
    "provider": string;
    "model": string;
    "temperature": number;
    "max_tokens": number;
    "enable_image_recognition": boolean;

    /**
     * 每日0点或配置的时间进行记忆整理
     */
    "memory_organize_time": string;

    /** Creates a new AgentConfig instance. */
    constructor($$source: Partial<AgentConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("agent_name" in $$source)) {
            this["agent_name"] = "";
        }
        if (!("workspace" in $$source)) {
            this["workspace"] = "";
        }
        if (!("provider" in $$source)) {
            this["provider"] = "";
        }
        if (!("model" in $$source)) {
            this["model"] = "";
        }
        if (!("temperature" in $$source)) {
            this["temperature"] = 0;
        }
        if (!("max_tokens" in $$source)) {
            this["max_tokens"] = 0;
        }
        if (!("enable_image_recognition" in $$source)) {
            this["enable_image_recognition"] = false;
        }
        if (!("memory_organize_time" in $$source)) {
            this["memory_organize_time"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): AgentConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentConfig($$parsedSource as Partial<AgentConfig>);
    }
}

export class BrowserConfig {
    "id": string;

    /**
     * 浏览器用户数据目录，用于持久化cookies、登录状态等
     */
    "data_dir": string;

    /** Creates a new BrowserConfig instance. */
    constructor($$source: Partial<BrowserConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("data_dir" in $$source)) {
            this["data_dir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BrowserConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): BrowserConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BrowserConfig($$parsedSource as Partial<BrowserConfig>);
    }
}

export class ChannelConfig {
    "id": string;
    "channel_name": string;
    "type": string;
    "enabled": boolean;
    "agent": string;

    /**
     * feishu
     */
    "app_id"?: string;
    "app_secret"?: string;

    /**
     * web
     */
    "host_address"?: string;
    "token"?: string;

    /**
     * wechat ilink
     * 凭证存储路径，默认 ~/.wechatbot/{name}_credentials.json
     */
    "cred_path"?: string;

    /** Creates a new ChannelConfig instance. */
    constructor($$source: Partial<ChannelConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("channel_name" in $$source)) {
            this["channel_name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("agent" in $$source)) {
            this["agent"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChannelConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ChannelConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChannelConfig($$parsedSource as Partial<ChannelConfig>);
    }
}

export class ContentBlock {
    /**
     * "text", "image"
     */
    "Type": string;

    /**
     * 文本内容（Type="text"时使用）
     */
    "Text": string;

    /**
     * 图片base64数据（Type="image"时使用）
     */
    "ImageData": string;

    /**
     * 图片MIME类型，如 "image/png", "image/jpeg"
     */
    "MediaType": string;

    /** Creates a new ContentBlock instance. */
    constructor($$source: Partial<ContentBlock> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }
        if (!("ImageData" in $$source)) {
            this["ImageData"] = "";
        }
        if (!("MediaType" in $$source)) {
            this["MediaType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContentBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): ContentBlock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContentBlock($$parsedSource as Partial<ContentBlock>);
    }
}

export class EmotionAction {
    "motion_group"?: string;
    "motion_no"?: number;
    "expression_id"?: string;

    /** Creates a new EmotionAction instance. */
    constructor($$source: Partial<EmotionAction> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmotionAction instance from a string or object.
     */
    static createFrom($$source: any = {}): EmotionAction {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EmotionAction($$parsedSource as Partial<EmotionAction>);
    }
}

export class EmotionMapping {
    "id": string;
    "mappings": { [_ in string]?: EmotionAction | null };

    /** Creates a new EmotionMapping instance. */
    constructor($$source: Partial<EmotionMapping> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("mappings" in $$source)) {
            this["mappings"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EmotionMapping instance from a string or object.
     */
    static createFrom($$source: any = {}): EmotionMapping {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("mappings" in $$parsedSource) {
            $$parsedSource["mappings"] = $$createField1_0($$parsedSource["mappings"]);
        }
        return new EmotionMapping($$parsedSource as Partial<EmotionMapping>);
    }
}

export class Live2DConfig {
    "id": string;
    "enabled": boolean;
    "model_dir": string;
    "model_name": string;
    "width": number;
    "height": number;
    "x": number;
    "y": number;

    /** Creates a new Live2DConfig instance. */
    constructor($$source: Partial<Live2DConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("model_dir" in $$source)) {
            this["model_dir"] = "";
        }
        if (!("model_name" in $$source)) {
            this["model_name"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }
        if (!("x" in $$source)) {
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Live2DConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): Live2DConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Live2DConfig($$parsedSource as Partial<Live2DConfig>);
    }
}

export class Live2DMotion {
    "group": string;
    "no": number;

    /** Creates a new Live2DMotion instance. */
    constructor($$source: Partial<Live2DMotion> = {}) {
        if (!("group" in $$source)) {
            this["group"] = "";
        }
        if (!("no" in $$source)) {
            this["no"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Live2DMotion instance from a string or object.
     */
    static createFrom($$source: any = {}): Live2DMotion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Live2DMotion($$parsedSource as Partial<Live2DMotion>);
    }
}

export class McpConfig {
    "id": string;
    "name": string;
    "command": string;
    "args": string[];
    "env": { [_ in string]?: string };
    "cwd"?: string;

    /**
     * 通信协议，默认stdio，以后可能扩展到http、sse等
     * 通信协议，默认stdio，以后可能扩展到http、sse等
     */
    "transport_type"?: string;

    /**
     * 通信地址，用于http、sse等
     */
    "url"?: string;

    /**
     * 自定义HTTP请求头，用于http、sse等
     */
    "headers"?: { [_ in string]?: string };

    /** Creates a new McpConfig instance. */
    constructor($$source: Partial<McpConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("command" in $$source)) {
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            this["args"] = [];
        }
        if (!("env" in $$source)) {
            this["env"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new McpConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): McpConfig {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType4;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField3_0($$parsedSource["args"]);
        }
        if ("env" in $$parsedSource) {
            $$parsedSource["env"] = $$createField4_0($$parsedSource["env"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField8_0($$parsedSource["headers"]);
        }
        return new McpConfig($$parsedSource as Partial<McpConfig>);
    }
}

export class Message {
    "Role": string;

    /**
     * 纯文本内容（向后兼容）
     */
    "Content": string;

    /**
     * 多内容块（可选，用于多模态消息）
     */
    "Contents": ContentBlock[];
    "Timestamp": time$0.Time;
    "ToolCalls": ToolCall[];

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("Role" in $$source)) {
            this["Role"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("Contents" in $$source)) {
            this["Contents"] = [];
        }
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = null;
        }
        if (!("ToolCalls" in $$source)) {
            this["ToolCalls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField2_0 = $$createType6;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Contents" in $$parsedSource) {
            $$parsedSource["Contents"] = $$createField2_0($$parsedSource["Contents"]);
        }
        if ("ToolCalls" in $$parsedSource) {
            $$parsedSource["ToolCalls"] = $$createField4_0($$parsedSource["ToolCalls"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class ProviderConfig {
    "id": string;
    "provider_name": string;

    /**
     * openai/anthropic/ollama/...
     */
    "type": string;
    "api_key": string;
    "base_url"?: string;

    /** Creates a new ProviderConfig instance. */
    constructor($$source: Partial<ProviderConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("provider_name" in $$source)) {
            this["provider_name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("api_key" in $$source)) {
            this["api_key"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): ProviderConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderConfig($$parsedSource as Partial<ProviderConfig>);
    }
}

export class SkillConfig {
    "id": string;
    "global_path": string;

    /** Creates a new SkillConfig instance. */
    constructor($$source: Partial<SkillConfig> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("global_path" in $$source)) {
            this["global_path"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): SkillConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SkillConfig($$parsedSource as Partial<SkillConfig>);
    }
}

export class ToolCall {
    "ID": string;
    "Name": string;
    "Arguments": string;
    "Result": string;

    /** Creates a new ToolCall instance. */
    constructor($$source: Partial<ToolCall> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Arguments" in $$source)) {
            this["Arguments"] = "";
        }
        if (!("Result" in $$source)) {
            this["Result"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCall {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCall($$parsedSource as Partial<ToolCall>);
    }
}

// Private type creation functions
const $$createType0 = EmotionAction.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
const $$createType5 = ContentBlock.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = ToolCall.createFrom;
const $$createType8 = $Create.Array($$createType7);
