// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

export class ContentBlock {
    /**
     * "text", "image"
     */
    "Type": string;

    /**
     * 文本内容（Type="text"时使用）
     */
    "Text": string;

    /**
     * 图片base64数据（Type="image"时使用）
     */
    "ImageData": string;

    /**
     * 图片MIME类型，如 "image/png", "image/jpeg"
     */
    "MediaType": string;

    /** Creates a new ContentBlock instance. */
    constructor($$source: Partial<ContentBlock> = {}) {
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Text" in $$source)) {
            this["Text"] = "";
        }
        if (!("ImageData" in $$source)) {
            this["ImageData"] = "";
        }
        if (!("MediaType" in $$source)) {
            this["MediaType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContentBlock instance from a string or object.
     */
    static createFrom($$source: any = {}): ContentBlock {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ContentBlock($$parsedSource as Partial<ContentBlock>);
    }
}

export class Live2DMotion {
    "Group": string;
    "No": number;
    "Name": string;

    /** Creates a new Live2DMotion instance. */
    constructor($$source: Partial<Live2DMotion> = {}) {
        if (!("Group" in $$source)) {
            this["Group"] = "";
        }
        if (!("No" in $$source)) {
            this["No"] = 0;
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Live2DMotion instance from a string or object.
     */
    static createFrom($$source: any = {}): Live2DMotion {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Live2DMotion($$parsedSource as Partial<Live2DMotion>);
    }
}

export class Message {
    "Role": string;

    /**
     * 纯文本内容（向后兼容）
     */
    "Content": string;

    /**
     * 多内容块（可选，用于多模态消息）
     */
    "Contents": ContentBlock[];
    "Timestamp": time$0.Time;
    "ToolCalls": ToolCall[];

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("Role" in $$source)) {
            this["Role"] = "";
        }
        if (!("Content" in $$source)) {
            this["Content"] = "";
        }
        if (!("Contents" in $$source)) {
            this["Contents"] = [];
        }
        if (!("Timestamp" in $$source)) {
            this["Timestamp"] = null;
        }
        if (!("ToolCalls" in $$source)) {
            this["ToolCalls"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField2_0 = $$createType1;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Contents" in $$parsedSource) {
            $$parsedSource["Contents"] = $$createField2_0($$parsedSource["Contents"]);
        }
        if ("ToolCalls" in $$parsedSource) {
            $$parsedSource["ToolCalls"] = $$createField4_0($$parsedSource["ToolCalls"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

export class ToolCall {
    "ID": string;
    "Name": string;
    "Arguments": string;
    "Result": string;

    /** Creates a new ToolCall instance. */
    constructor($$source: Partial<ToolCall> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Arguments" in $$source)) {
            this["Arguments"] = "";
        }
        if (!("Result" in $$source)) {
            this["Result"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     */
    static createFrom($$source: any = {}): ToolCall {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolCall($$parsedSource as Partial<ToolCall>);
    }
}

// Private type creation functions
const $$createType0 = ContentBlock.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ToolCall.createFrom;
const $$createType3 = $Create.Array($$createType2);
