// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * EntityType 实体类型
 */
export enum EntityType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * @用户
     */
    EntityTypeMention = "mention",

    /**
     * @全体成员
     */
    EntityTypeMentionAll = "mention_all",

    /**
     * 链接
     */
    EntityTypeLink = "link",

    /**
     * 话题标签
     */
    EntityTypeHashtag = "hashtag",

    /**
     * 机器人命令
     */
    EntityTypeBotCommand = "bot_command",

    /**
     * 邮箱地址
     */
    EntityTypeEmail = "email",
};

/**
 * Keyboard 交互键盘
 */
export class Keyboard {
    /**
     * 是否为内联键盘（显示在消息下方）
     */
    "inline": boolean;
    "rows": KeyboardRow[];

    /**
     * 是否可调整大小
     */
    "resizeable"?: boolean;

    /**
     * 是否一次性键盘
     */
    "one_time"?: boolean;

    /** Creates a new Keyboard instance. */
    constructor($$source: Partial<Keyboard> = {}) {
        if (!("inline" in $$source)) {
            this["inline"] = false;
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Keyboard instance from a string or object.
     */
    static createFrom($$source: any = {}): Keyboard {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        return new Keyboard($$parsedSource as Partial<Keyboard>);
    }
}

/**
 * KeyboardButton 键盘按钮
 */
export class KeyboardButton {
    /**
     * 按钮文本
     */
    "text": string;

    /**
     * 回调数据
     */
    "data"?: string;

    /**
     * 链接URL
     */
    "url"?: string;

    /**
     * 请求联系人
     */
    "request_contact"?: boolean;

    /**
     * 请求位置
     */
    "request_location"?: boolean;

    /** Creates a new KeyboardButton instance. */
    constructor($$source: Partial<KeyboardButton> = {}) {
        if (!("text" in $$source)) {
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyboardButton instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyboardButton {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KeyboardButton($$parsedSource as Partial<KeyboardButton>);
    }
}

/**
 * KeyboardRow 键盘行
 */
export class KeyboardRow {
    "buttons": KeyboardButton[];

    /** Creates a new KeyboardRow instance. */
    constructor($$source: Partial<KeyboardRow> = {}) {
        if (!("buttons" in $$source)) {
            this["buttons"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KeyboardRow instance from a string or object.
     */
    static createFrom($$source: any = {}): KeyboardRow {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("buttons" in $$parsedSource) {
            $$parsedSource["buttons"] = $$createField0_0($$parsedSource["buttons"]);
        }
        return new KeyboardRow($$parsedSource as Partial<KeyboardRow>);
    }
}

/**
 * LocationInfo 位置信息
 */
export class LocationInfo {
    /**
     * 纬度
     */
    "latitude": number;

    /**
     * 经度
     */
    "longitude": number;

    /**
     * 位置名称
     */
    "title"?: string;

    /**
     * 详细地址
     */
    "address"?: string;

    /** Creates a new LocationInfo instance. */
    constructor($$source: Partial<LocationInfo> = {}) {
        if (!("latitude" in $$source)) {
            this["latitude"] = 0;
        }
        if (!("longitude" in $$source)) {
            this["longitude"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocationInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): LocationInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocationInfo($$parsedSource as Partial<LocationInfo>);
    }
}

/**
 * MediaContent 媒体内容
 */
export class MediaContent {
    /**
     * 媒体类型
     */
    "type": MediaType;

    /**
     * 媒体URL
     */
    "url"?: string;

    /**
     * 本地文件路径
     */
    "file_path"?: string;

    /**
     * 缩略图URL
     */
    "thumbnail"?: string;

    /**
     * 文件大小
     */
    "size"?: number;

    /**
     * 时长（秒，音视频）
     */
    "duration"?: number;

    /**
     * 宽度（图片/视频）
     */
    "width"?: number;

    /**
     * 高度（图片/视频）
     */
    "height"?: number;

    /**
     * 文件名
     */
    "file_name"?: string;

    /**
     * MIME类型
     */
    "mime_type"?: string;

    /** Creates a new MediaContent instance. */
    constructor($$source: Partial<MediaContent> = {}) {
        if (!("type" in $$source)) {
            this["type"] = MediaType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MediaContent instance from a string or object.
     */
    static createFrom($$source: any = {}): MediaContent {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MediaContent($$parsedSource as Partial<MediaContent>);
    }
}

/**
 * MediaType 媒体类型
 */
export enum MediaType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MediaTypeImage = "image",
    MediaTypeVideo = "video",
    MediaTypeAudio = "audio",
    MediaTypeFile = "file",
};

/**
 * Message 统一的消息结构
 */
export class Message {
    /**
     * 基础信息
     * 消息类型
     */
    "type": MessageType;

    /**
     * 文本内容
     */
    "content": string;

    /**
     * 消息实体
     */
    "entities"?: MessageEntity[];

    /**
     * 媒体内容
     * 媒体内容
     */
    "media"?: MediaContent | null;

    /**
     * 关系信息
     * 消息引用（回复、转发）
     */
    "reference"?: MessageReference | null;

    /**
     * 位置信息（当Type=MessageTypeLocation时）
     */
    "location"?: LocationInfo | null;

    /**
     * 交互元素（键盘、按钮等）
     */
    "keyboard"?: Keyboard | null;

    /**
     * 元数据
     */
    "metadata": MessageMetadata;

    /** Creates a new Message instance. */
    constructor($$source: Partial<Message> = {}) {
        if (!("type" in $$source)) {
            this["type"] = MessageType.$zero;
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("metadata" in $$source)) {
            this["metadata"] = (new MessageMetadata());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     */
    static createFrom($$source: any = {}): Message {
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        const $$createField4_0 = $$createType9;
        const $$createField5_0 = $$createType11;
        const $$createField6_0 = $$createType13;
        const $$createField7_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entities" in $$parsedSource) {
            $$parsedSource["entities"] = $$createField2_0($$parsedSource["entities"]);
        }
        if ("media" in $$parsedSource) {
            $$parsedSource["media"] = $$createField3_0($$parsedSource["media"]);
        }
        if ("reference" in $$parsedSource) {
            $$parsedSource["reference"] = $$createField4_0($$parsedSource["reference"]);
        }
        if ("location" in $$parsedSource) {
            $$parsedSource["location"] = $$createField5_0($$parsedSource["location"]);
        }
        if ("keyboard" in $$parsedSource) {
            $$parsedSource["keyboard"] = $$createField6_0($$parsedSource["keyboard"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField7_0($$parsedSource["metadata"]);
        }
        return new Message($$parsedSource as Partial<Message>);
    }
}

/**
 * MessageEntity 消息实体，表示文本中的特殊元素
 */
export class MessageEntity {
    /**
     * 实体类型
     */
    "type": EntityType;

    /**
     * 在文本中的起始位置
     */
    "offset": number;

    /**
     * 长度
     */
    "length": number;

    /**
     * 链接URL
     */
    "url"?: string;

    /**
     * @的用户ID
     */
    "user_id"?: string;

    /**
     * @的内容（如@全体成员）
     */
    "mention"?: string;

    /** Creates a new MessageEntity instance. */
    constructor($$source: Partial<MessageEntity> = {}) {
        if (!("type" in $$source)) {
            this["type"] = EntityType.$zero;
        }
        if (!("offset" in $$source)) {
            this["offset"] = 0;
        }
        if (!("length" in $$source)) {
            this["length"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageEntity instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageEntity {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageEntity($$parsedSource as Partial<MessageEntity>);
    }
}

/**
 * MessageForwardInfo 转发信息
 */
export class MessageForwardInfo {
    /**
     * 来源聊天ID
     */
    "from_chat_id": string;

    /**
     * 来源消息ID
     */
    "from_message_id": string;

    /**
     * 来源发送者名称
     */
    "from_sender_name": string;

    /**
     * 来源发送者ID
     */
    "from_sender_id": string;

    /** Creates a new MessageForwardInfo instance. */
    constructor($$source: Partial<MessageForwardInfo> = {}) {
        if (!("from_chat_id" in $$source)) {
            this["from_chat_id"] = "";
        }
        if (!("from_message_id" in $$source)) {
            this["from_message_id"] = "";
        }
        if (!("from_sender_name" in $$source)) {
            this["from_sender_name"] = "";
        }
        if (!("from_sender_id" in $$source)) {
            this["from_sender_id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageForwardInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageForwardInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageForwardInfo($$parsedSource as Partial<MessageForwardInfo>);
    }
}

/**
 * MessageMetadata 消息元数据
 */
export class MessageMetadata {
    /**
     * 消息ID
     */
    "message_id": string;

    /**
     * 发送者ID
     */
    "sender_id": string;

    /**
     * 发送者名称
     */
    "sender_name": string;

    /**
     * 聊天ID
     */
    "chat_id": string;

    /**
     * 聊天名称
     */
    "chat_name": string;

    /**
     * 聊天类型, p2p group topic?
     */
    "chat_type": string;

    /**
     * 发送时间
     */
    "timestamp": time$0.Time;

    /**
     * 编辑时间
     */
    "edit_timestamp"?: time$0.Time | null;

    /**
     * 转发信息
     */
    "forward_from"?: MessageForwardInfo | null;

    /**
     * 回复的消息ID
     */
    "reply_to_id"?: string;

    /**
     * 是否被置顶
     */
    "pinned"?: boolean;

    /**
     * 查看次数
     */
    "views"?: number;

    /**
     * 转发次数
     */
    "forwards"?: number;

    /**
     * 渠道标识
     */
    "channel": string;

    /**
     * 会话进度
     * 会话进度（0-1）
     */
    "session_percent"?: number;

    /** Creates a new MessageMetadata instance. */
    constructor($$source: Partial<MessageMetadata> = {}) {
        if (!("message_id" in $$source)) {
            this["message_id"] = "";
        }
        if (!("sender_id" in $$source)) {
            this["sender_id"] = "";
        }
        if (!("sender_name" in $$source)) {
            this["sender_name"] = "";
        }
        if (!("chat_id" in $$source)) {
            this["chat_id"] = "";
        }
        if (!("chat_name" in $$source)) {
            this["chat_name"] = "";
        }
        if (!("chat_type" in $$source)) {
            this["chat_type"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = null;
        }
        if (!("channel" in $$source)) {
            this["channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageMetadata instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageMetadata {
        const $$createField8_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("forward_from" in $$parsedSource) {
            $$parsedSource["forward_from"] = $$createField8_0($$parsedSource["forward_from"]);
        }
        return new MessageMetadata($$parsedSource as Partial<MessageMetadata>);
    }
}

/**
 * MessageReference 消息引用
 */
export class MessageReference {
    /**
     * 被引用的消息ID
     */
    "message_id": string;

    /**
     * 所属聊天ID
     */
    "chat_id": string;

    /**
     * 发送者ID
     */
    "sender_id": string;

    /**
     * 发送者名称
     */
    "sender_name": string;

    /**
     * 内容摘要
     */
    "content": string;

    /**
     * 消息类型
     */
    "message_type": MessageType;

    /**
     * 引用类型
     */
    "reference_type": ReferenceType;

    /** Creates a new MessageReference instance. */
    constructor($$source: Partial<MessageReference> = {}) {
        if (!("message_id" in $$source)) {
            this["message_id"] = "";
        }
        if (!("chat_id" in $$source)) {
            this["chat_id"] = "";
        }
        if (!("sender_id" in $$source)) {
            this["sender_id"] = "";
        }
        if (!("sender_name" in $$source)) {
            this["sender_name"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("message_type" in $$source)) {
            this["message_type"] = MessageType.$zero;
        }
        if (!("reference_type" in $$source)) {
            this["reference_type"] = ReferenceType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MessageReference instance from a string or object.
     */
    static createFrom($$source: any = {}): MessageReference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MessageReference($$parsedSource as Partial<MessageReference>);
    }
}

/**
 * MessageType 消息类型
 */
export enum MessageType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 纯文本
     */
    MessageTypeText = "text",

    /**
     * 图片
     */
    MessageTypeImage = "image",

    /**
     * 视频
     */
    MessageTypeVideo = "video",

    /**
     * 音频
     */
    MessageTypeAudio = "audio",

    /**
     * 语音消息
     */
    MessageTypeVoice = "voice",

    /**
     * 文件
     */
    MessageTypeFile = "file",

    /**
     * 位置
     */
    MessageTypeLocation = "location",

    /**
     * 贴纸
     */
    MessageTypeSticker = "sticker",

    /**
     * 富媒体（图文、卡片等）
     */
    MessageTypeRichMedia = "rich_media",
};

/**
 * ReferenceType 引用类型
 */
export enum ReferenceType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * 回复
     */
    ReferenceTypeReply = "reply",

    /**
     * 转发
     */
    ReferenceTypeForward = "forward",

    /**
     * 引用
     */
    ReferenceTypeQuote = "quote",
};

// Private type creation functions
const $$createType0 = KeyboardRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = KeyboardButton.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = MessageEntity.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = MediaContent.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = MessageReference.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = LocationInfo.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = Keyboard.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = MessageMetadata.createFrom;
const $$createType15 = MessageForwardInfo.createFrom;
const $$createType16 = $Create.Nullable($$createType15);
