// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as bus$0 from "../../../../yockii/wangshu/pkg/bus/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "chat-message": bus$0.Message;
        }
    }
}
