// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as agent$0 from "../agent/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../types/models.js";

export function GetHistoryMessages(fetchedLength: number, length: number): $CancellablePromise<types$0.Message[]> {
    return $Call.ByID(3715178725, fetchedLength, length).then(($result: any) => {
        return $$createType1($result);
    });
}

export function HandleMessage(content: string): $CancellablePromise<void> {
    return $Call.ByID(2613553446, content);
}

export function SetAgent(agent: agent$0.Agent | null): $CancellablePromise<void> {
    return $Call.ByID(2869054500, agent);
}

// Private type creation functions
const $$createType0 = types$0.Message.createFrom;
const $$createType1 = $Create.Array($$createType0);
