// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function GetConfig(): $CancellablePromise<config$0.Config | null> {
    return $Call.ByID(2057583173).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetModelList(modelDir: string): $CancellablePromise<string[]> {
    return $Call.ByID(2928336588, modelDir).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetModelPath(modelDir: string, modelName: string): $CancellablePromise<string> {
    return $Call.ByID(4265646099, modelDir, modelName);
}

export function SaveConfig(cfg: config$0.Config | null): $CancellablePromise<void> {
    return $Call.ByID(664206806, cfg);
}

export function SelectFolder(title: string, defaultPath: string): $CancellablePromise<string> {
    return $Call.ByID(4068177109, title, defaultPath);
}

export function ValidateConfig(): $CancellablePromise<void> {
    return $Call.ByID(2001787529);
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
