// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Error(title: string, msg: string): $CancellablePromise<void> {
    return $Call.ByID(1830364899, title, msg);
}

export function Info(title: string, msg: string): $CancellablePromise<void> {
    return $Call.ByID(3707272927, title, msg);
}

export function Warning(title: string, msg: string): $CancellablePromise<void> {
    return $Call.ByID(3457689789, title, msg);
}
