// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

export function ExitEditMode(): $CancellablePromise<void> {
    return $Call.ByID(1230589064);
}

export function GetLive2DConfig(): $CancellablePromise<config$0.Live2DConfig | null> {
    return $Call.ByID(1944404803).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetModelFile(): $CancellablePromise<string> {
    return $Call.ByID(2429407108);
}

export function IsEditMode(): $CancellablePromise<boolean> {
    return $Call.ByID(874476260);
}

export function SaveLive2DConfig(): $CancellablePromise<void> {
    return $Call.ByID(2940702932);
}

export function UpdateLive2DWindowPosition(x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(2541802877, x, y);
}

export function UpdateLive2DWindowSize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(16244811, width, height);
}

// Private type creation functions
const $$createType0 = config$0.Live2DConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
