// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function HideChatWindow(): $CancellablePromise<void> {
    return $Call.ByID(3992615265);
}

export function HideConfigWindow(): $CancellablePromise<void> {
    return $Call.ByID(452590901);
}

export function HideLive2DWindow(): $CancellablePromise<void> {
    return $Call.ByID(3633599899);
}

export function ShowChatWindow(): $CancellablePromise<void> {
    return $Call.ByID(1675390944);
}

export function ShowConfigWindow(): $CancellablePromise<void> {
    return $Call.ByID(1082889232);
}

export function ShowLive2DWindow(): $CancellablePromise<void> {
    return $Call.ByID(3615451778);
}
